# MLA Brand - GitHub Pages Configuration
title: MLA Brand API
description: Blog data API for Flutter mobile application
url: https://dmouli408.github.io
baseurl: /mla-brand

# GitHub Pages settings
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md

# CORS headers for API endpoints
plugins:
  - jekyll-cors

cors:
  allow_origin: "*"
  allow_methods: "GET, POST, OPTIONS"
  allow_headers: "*"

# Exclude unnecessary files
exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
